### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [ferateck/project7#1]
A couple issues I'd like fixed here:
- When I submit the form, I expect to see my changes saved in the form, as specified in the project (`every form field should always show the current parameters`). You can do [something like this](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) to make sure the current params are reflected in the form.
- I see a typo for the January option in the months select.

Let me know when those are resolved and I'll take another look! If you have questions about how to fix them, also just let me know.

**Comment by ferateck** [comment]
Thanks for the help, but unfortunately i need more. The part of the  
cat app taht you showed me got me able to keep the year in the form  
field, but for some reason in my two select fields what is selected  
will not stay, and can not seem to find a solution that works. Thanks  
for pointing out the spelling error, and thanks for all the help!  
                                       ~matt

Quoting Chris Fritz notifications@github.com:

**Comment by ferateck** [comment]
Thanks for the help in class, it is now totally done and ready for  
your re-review

Quoting Chris Fritz notifications@github.com:

**Comment by chrisvfritz** [comment]
:+1: Much better!
